import { worldLeague, type WorldLeague } from "./world-types";

/* ------------------------------------------------------------------ */
/*  The Americas & the rest of the world — every top division outside  */
/*  Europe that a career can realistically pass through: MLS and Liga  */
/*  MX, the whole South American spine, the Saudi and Asian money      */
/*  leagues, and the African pyramids that produce so much of the      */
/*  game's talent. Top flight only (division 1). Compact tuples:       */
/*  [name, short, reputation, colour1, colour2, recruitment, needs,    */
/*   objective]                                                        */
/*  Reputation is the hidden 0–100 pull of the club, on the same scale */
/*  as Europe: 100 = Real Madrid, ~70 = Braga, ~50 = lower divisions.  */
/* ------------------------------------------------------------------ */

export const AMERICAS_ROW_LEAGUES: WorldLeague[] = [
  /* ---------------- United States · Major League Soccer ---------------- */
  worldLeague("usa-mls", "Major League Soccer", "United States", 1, 62, [
    ["Inter Miami CF", "MIA", 68, "#f7b5cd", "#231f20", "showcase", ["CB", "CDM", "RW"], "Turn global star power into a first MLS Cup"],
    ["Los Angeles FC", "LFC", 66, "#231f20", "#c39e6d", "showcase", ["ST", "CM", "CB"], "Win MLS Cup and the CONCACAF Champions Cup"],
    ["LA Galaxy", "LAG", 65, "#00245d", "#ffd200", "showcase", ["ST", "CAM", "CB"], "Defend the crown with another marquee signing"],
    ["Columbus Crew", "CLB", 63, "#fff200", "#231f20", "development", ["ST", "LB", "CDM"], "Keep playing the best football in the league"],
    ["Seattle Sounders FC", "SEA", 63, "#5d9741", "#005595", "midTable", ["ST", "CM", "RB"], "Return to the top of the Western Conference"],
    ["FC Cincinnati", "CIN", 62, "#f05323", "#263b80", "midTable", ["ST", "CAM", "CB"], "Convert a Supporters' Shield into MLS Cup"],
    ["Atlanta United FC", "ATL", 61, "#80000b", "#231f20", "showcase", ["CAM", "ST", "CDM"], "Fill the stadium and win silverware again"],
    ["Philadelphia Union", "PHI", 61, "#0d1b2a", "#b49759", "development", ["ST", "RW", "CB"], "Sell an academy graduate for a record fee"],
    ["New York City FC", "NYC", 60, "#6cabdd", "#041e42", "development", ["CB", "CM", "ST"], "Open the new stadium as contenders"],
    ["New York Red Bulls", "NYR", 60, "#ed1e36", "#23326a", "development", ["ST", "CM", "LB"], "Press teams into submission and finally win MLS Cup"],
    ["Portland Timbers", "POR", 59, "#004812", "#eae827", "midTable", ["CB", "CDM", "ST"], "Make the play-offs and give the Timbers Army a run"],
    ["Orlando City SC", "ORL", 58, "#612b9b", "#fde192", "midTable", ["ST", "RW", "CB"], "Go deep in the play-offs"],
    ["Austin FC", "AUS", 58, "#00b140", "#231f20", "midTable", ["ST", "CAM", "CB"], "Get back to a Western Conference final"],
    ["San Diego FC", "SDF", 57, "#00a9e0", "#12284c", "showcase", ["ST", "CM", "CB"], "Build an expansion side that wins straight away"],
    ["Nashville SC", "NSH", 57, "#ece83a", "#1d1d1b", "midTable", ["ST", "LW", "CDM"], "Stay a play-off side every season"],
    ["Minnesota United FC", "MIN", 56, "#8cd2f4", "#231f20", "midTable", ["ST", "CAM", "RB"], "Take the next step from play-off regulars to contenders"],
    ["Real Salt Lake", "RSL", 56, "#b30838", "#013a81", "midTable", ["ST", "CB", "CM"], "Sneak into the play-offs on a modest budget"],
    ["Charlotte FC", "CLT", 55, "#1a85c8", "#231f20", "survival", ["ST", "CDM", "CB"], "Establish the club as a play-off side"],
  ]),

  /* ---------------- Mexico · Liga MX ---------------- */
  worldLeague("mex-mx", "Liga MX", "Mexico", 1, 66, [
    ["Club América", "AME", 72, "#ffe100", "#0a1a6b", "elite", ["ST", "CB", "CM"], "Win another Liga MX title and rule the continent"],
    ["Tigres UANL", "TIG", 70, "#ffb81c", "#00274c", "showcase", ["ST", "CAM", "CB"], "Sign a continental star and win the Clausura"],
    ["CF Monterrey", "MTY", 70, "#00256b", "#ffffff", "showcase", ["ST", "CM", "CB"], "Win the CONCACAF Champions Cup"],
    ["Cruz Azul", "CAZ", 68, "#1a53b0", "#ffffff", "midTable", ["ST", "CDM", "LB"], "Turn strong league form into a ninth title"],
    ["Chivas de Guadalajara", "GDL", 67, "#e2001a", "#ffffff", "domestic", ["ST", "CB", "CAM"], "Win a title with an all-Mexican squad"],
    ["Deportivo Toluca", "TOL", 66, "#e2001a", "#ffffff", "midTable", ["CB", "CM", "RW"], "Defend the championship"],
    ["CF Pachuca", "PAC", 65, "#003da5", "#ffffff", "development", ["ST", "RW", "CB"], "Develop and sell the next Mexican export"],
    ["Pumas UNAM", "PUM", 64, "#00224e", "#e8a800", "development", ["ST", "CM", "CB"], "Promote from the cantera and reach the liguilla"],
    ["Club León", "LEO", 63, "#0a7d3c", "#ffffff", "midTable", ["ST", "CAM", "CB"], "Get back into the play-off places"],
    ["Santos Laguna", "SLA", 61, "#00a94f", "#ffffff", "development", ["ST", "LW", "CDM"], "Rebuild around young players and climb the table"],
    ["Atlas FC", "ATS", 60, "#e2001a", "#231f20", "midTable", ["ST", "CB", "CM"], "Recapture the title-winning spirit"],
    ["Club Tijuana", "TIJ", 59, "#e2001a", "#231f20", "midTable", ["ST", "RB", "CAM"], "Qualify for the liguilla"],
    ["Atlético San Luis", "SLP", 56, "#e2001a", "#ffffff", "survival", ["CB", "CDM", "ST"], "Avoid the bottom of the percentage table"],
    ["Club Puebla", "PUE", 56, "#003da5", "#ffffff", "survival", ["ST", "CB", "GK"], "Stay clear of relegation trouble"],
    ["Club Necaxa", "NEC", 57, "#e2001a", "#ffffff", "survival", ["ST", "CM", "CB"], "Finish above the play-in line"],
    ["Querétaro FC", "QRO", 55, "#231f20", "#1a53b0", "survival", ["CB", "CDM", "ST"], "Survive another season in Liga MX"],
    ["Mazatlán FC", "MAZ", 55, "#6a2c8e", "#ffffff", "survival", ["ST", "LB", "CB"], "Climb out of the bottom four"],
    ["FC Juárez", "JUA", 55, "#009639", "#231f20", "survival", ["ST", "CB", "CM"], "Reach the play-in for the first time in years"],
  ]),

  /* ---------------- Brazil · Brasileirão Série A ---------------- */
  worldLeague("bra-sa", "Campeonato Brasileiro Série A", "Brazil", 1, 76, [
    ["Flamengo", "FLA", 84, "#c52613", "#231f20", "domestic", ["CB", "CM", "ST"], "Win the Copa Libertadores again"],
    ["Palmeiras", "PAL", 84, "#0a7d3c", "#ffffff", "domestic", ["ST", "CAM", "CB"], "Win a third Libertadores in five years"],
    ["Botafogo", "BOT", 79, "#231f20", "#ffffff", "domestic", ["ST", "CM", "RB"], "Prove the Libertadores was no accident"],
    ["São Paulo", "SAO", 78, "#e2001a", "#231f20", "domestic", ["ST", "CB", "CDM"], "Return to the Libertadores places"],
    ["Corinthians", "COR", 78, "#231f20", "#ffffff", "domestic", ["ST", "CM", "LB"], "Give the Fiel a title to sing about"],
    ["Atlético Mineiro", "CAM", 77, "#231f20", "#ffffff", "domestic", ["ST", "CAM", "CB"], "Win the Libertadores for the second time"],
    ["Internacional", "INT", 74, "#e2001a", "#ffffff", "domestic", ["ST", "CB", "CM"], "Finish in the Libertadores group stage places"],
    ["Grêmio", "GRE", 74, "#1a3aa8", "#231f20", "domestic", ["ST", "CDM", "LB"], "Get back among the Brasileirão's top four"],
    ["Cruzeiro", "CRU", 73, "#1a3aa8", "#ffffff", "domestic", ["ST", "RW", "CB"], "Turn heavy investment into a first title since 2014"],
    ["Santos", "SAN", 71, "#231f20", "#ffffff", "domestic", ["CB", "CDM", "ST"], "Rebuild Vila Belmiro around the next Menino da Vila"],
    ["Fluminense", "FLU", 75, "#7a1530", "#0a7d3c", "domestic", ["ST", "CM", "RB"], "Stay a continental force"],
    ["EC Bahia", "BAH", 70, "#005ca9", "#e2001a", "domestic", ["ST", "CAM", "CB"], "Qualify for the Libertadores again"],
    ["Fortaleza", "FOR", 70, "#003da5", "#e2001a", "domestic", ["ST", "CB", "CM"], "Stay in the top half and back in the Libertadores"],
    ["Vasco da Gama", "VAS", 70, "#231f20", "#ffffff", "domestic", ["CB", "CDM", "ST"], "Take a giant back to the Copa Libertadores"],
    ["Athletico Paranaense", "CAP", 68, "#e2001a", "#231f20", "development", ["ST", "CM", "LB"], "Sell to Europe and bounce straight back up the table"],
    ["Red Bull Bragantino", "RBB", 68, "#ffffff", "#e2001a", "development", ["ST", "RW", "CB"], "Turn young signings into European transfers"],
    ["EC Vitória", "VIT", 63, "#e2001a", "#231f20", "survival", ["ST", "CB", "GK"], "Stay in Série A"],
    ["EC Juventude", "JUV", 62, "#0a7d3c", "#ffffff", "survival", ["ST", "CB", "CDM"], "Beat the drop on the smallest budget in the division"],
  ]),

  /* ---------------- Argentina · Primera División ---------------- */
  worldLeague("arg-pd", "Primera División", "Argentina", 1, 72, [
    ["River Plate", "RIV", 80, "#e2001a", "#ffffff", "domestic", ["ST", "CB", "CM"], "Win the Copa Libertadores at the Monumental"],
    ["Boca Juniors", "BOC", 80, "#0a1a6b", "#f5c518", "domestic", ["ST", "CB", "CAM"], "End the wait for a seventh Libertadores"],
    ["Racing Club", "RAC", 74, "#6cabdd", "#ffffff", "domestic", ["ST", "CM", "LB"], "Add a league title to the continental cups"],
    ["Vélez Sarsfield", "VEL", 71, "#ffffff", "#1e4fbf", "development", ["ST", "CB", "RW"], "Keep producing and selling the next generation"],
    ["Independiente", "IND", 71, "#e2001a", "#231f20", "domestic", ["ST", "CDM", "CB"], "Restore the Rey de Copas to the Libertadores"],
    ["Estudiantes de La Plata", "EST", 70, "#e2001a", "#ffffff", "domestic", ["ST", "CM", "CB"], "Win another title with a hard-nosed side"],
    ["San Lorenzo", "SLO", 69, "#0a1a6b", "#e2001a", "domestic", ["ST", "CB", "CAM"], "Stabilise the club and reach the Libertadores"],
    ["Talleres", "TAL", 68, "#0a1a6b", "#ffffff", "domestic", ["ST", "RW", "CDM"], "Break into the top three and stay there"],
    ["Rosario Central", "ROS", 67, "#0a4e9b", "#f7c600", "domestic", ["ST", "CM", "CB"], "Win the Rosario derby and the league"],
    ["Lanús", "LAN", 66, "#7a0c1f", "#ffffff", "domestic", ["ST", "CAM", "CB"], "Turn Copa Sudamericana form into a league challenge"],
    ["Newell's Old Boys", "NOB", 66, "#e2001a", "#231f20", "development", ["ST", "CB", "CM"], "Bring the academy back to the first team"],
    ["Argentinos Juniors", "ARJ", 65, "#e2001a", "#ffffff", "development", ["ST", "CB", "CDM"], "Produce another Diego and sell him for a fortune"],
    ["Defensa y Justicia", "DEF", 63, "#f7c600", "#0a7d3c", "development", ["ST", "RB", "CM"], "Punch above the budget and qualify for a cup"],
    ["Huracán", "HUR", 63, "#ffffff", "#e2001a", "domestic", ["ST", "CB", "CM"], "Finish in the international places"],
    ["Banfield", "BAN", 61, "#0a7d3c", "#ffffff", "development", ["ST", "CAM", "CB"], "Blood the academy and stay mid-table"],
    ["Godoy Cruz", "GOD", 60, "#0a1a6b", "#ffffff", "survival", ["ST", "CB", "CDM"], "Climb clear of the relegation average"],
    ["Instituto", "INS", 58, "#e2001a", "#ffffff", "survival", ["ST", "CB", "GK"], "Consolidate in the Primera División"],
    ["Platense", "PLA", 57, "#6b4423", "#ffffff", "survival", ["ST", "CM", "CB"], "Stay up after the greatest season in the club's history"],
  ]),

  /* ---------------- Colombia · Categoría Primera A ---------------- */
  worldLeague("col-pa", "Categoría Primera A", "Colombia", 1, 60, [
    ["Atlético Nacional", "NAC", 66, "#0a7d3c", "#ffffff", "domestic", ["ST", "CB", "CM"], "Win the league and go deep in the Libertadores"],
    ["Millonarios", "MIL", 64, "#0a2a8b", "#ffffff", "domestic", ["ST", "CAM", "CB"], "Win a sixteenth league title"],
    ["Junior", "JUN", 63, "#e2001a", "#ffffff", "domestic", ["ST", "CM", "CB"], "Make Barranquilla a fortress again"],
    ["América de Cali", "AMC", 62, "#e2001a", "#ffffff", "domestic", ["ST", "CB", "LB"], "Return to the Libertadores group stage"],
    ["Deportivo Cali", "CAL", 61, "#0a7d3c", "#ffffff", "development", ["ST", "CB", "CM"], "Sell an academy product and stabilise the finances"],
    ["Independiente Medellín", "DIM", 60, "#e2001a", "#0a2a8b", "domestic", ["ST", "CDM", "CB"], "Reach the championship play-off final"],
    ["Independiente Santa Fe", "SFE", 60, "#e2001a", "#ffffff", "domestic", ["ST", "CB", "CAM"], "Win the Bogotá derby and the title"],
    ["Deportes Tolima", "TOL", 59, "#f7c600", "#7a0c1f", "domestic", ["ST", "CM", "RB"], "Get back into the top four"],
    ["Once Caldas", "ONC", 57, "#ffffff", "#e2001a", "domestic", ["ST", "CB", "CDM"], "Recapture the glory of 2004"],
    ["Águilas Doradas", "AGU", 54, "#f7c600", "#231f20", "development", ["ST", "RW", "CB"], "Trade young talent and reach the play-offs"],
    ["La Equidad", "EQU", 53, "#0a7d3c", "#ffffff", "development", ["ST", "CM", "CB"], "Stay competitive on the smallest wage bill"],
    ["Deportivo Pasto", "PAS", 53, "#e2001a", "#0a7d3c", "survival", ["ST", "CB", "GK"], "Keep top-flight football in Nariño"],
    ["Alianza FC", "ALI", 52, "#e2001a", "#ffffff", "survival", ["ST", "CB", "CDM"], "Stay clear of the relegation table"],
    ["Envigado FC", "ENV", 52, "#f7a600", "#ffffff", "development", ["ST", "CM", "CB"], "Sell another teenager to Europe"],
  ]),

  /* ---------------- Uruguay · Primera División ---------------- */
  worldLeague("uru-pd", "Primera División", "Uruguay", 1, 56, [
    ["Peñarol", "PEN", 64, "#f7c600", "#231f20", "domestic", ["ST", "CB", "CM"], "Win the league and reach a Libertadores semi-final"],
    ["Nacional", "NAC", 63, "#ffffff", "#0a2a8b", "domestic", ["ST", "CAM", "CB"], "Take the title back across Montevideo"],
    ["Defensor Sporting", "DSP", 54, "#7a0c1f", "#ffffff", "development", ["ST", "CB", "CM"], "Produce and sell the next Uruguayan international"],
    ["Liverpool FC Montevideo", "LMV", 54, "#231f20", "#0a2a8b", "domestic", ["ST", "CB", "CDM"], "Challenge the two giants for the title"],
    ["Montevideo City Torque", "TOR", 53, "#6cabdd", "#ffffff", "development", ["ST", "RW", "CB"], "Feed young players into a global club network"],
    ["Danubio", "DAN", 52, "#ffffff", "#231f20", "development", ["ST", "CM", "CB"], "Bring another academy generation through"],
    ["Montevideo Wanderers", "WAN", 50, "#231f20", "#ffffff", "development", ["ST", "CB", "LB"], "Sell well and finish in the top half"],
    ["Racing Club de Montevideo", "RCM", 50, "#6cabdd", "#ffffff", "survival", ["ST", "CB", "GK"], "Stay in the Primera División"],
    ["Cerro Largo", "CLA", 50, "#0a7d3c", "#ffffff", "survival", ["ST", "CM", "CB"], "Qualify for the Copa Sudamericana"],
    ["Plaza Colonia", "PLZ", 49, "#e2001a", "#ffffff", "survival", ["ST", "CB", "CDM"], "Keep a small-town club in the top flight"],
    ["Boston River", "BOS", 49, "#e2001a", "#ffffff", "survival", ["ST", "CB", "CM"], "Finish clear of the annual table's bottom"],
    ["Progreso", "PRO", 48, "#e2001a", "#231f20", "survival", ["ST", "GK", "CB"], "Survive another season among the elite"],
  ]),

  /* ---------------- Chile · Primera División ---------------- */
  worldLeague("chi-pd", "Primera División", "Chile", 1, 54, [
    ["Colo-Colo", "COL", 62, "#ffffff", "#231f20", "domestic", ["ST", "CB", "CM"], "Win the league and reach the Libertadores knockouts"],
    ["Universidad de Chile", "UCH", 60, "#0a2a8b", "#e2001a", "domestic", ["ST", "CAM", "CB"], "End the title drought at the Nacional"],
    ["Universidad Católica", "UCA", 60, "#ffffff", "#0a2a8b", "development", ["ST", "CB", "CM"], "Rebuild with academy players and win it back"],
    ["Palestino", "PAS", 52, "#0a7d3c", "#e2001a", "domestic", ["ST", "CM", "CB"], "Qualify for the Copa Libertadores"],
    ["Huachipato", "HUA", 51, "#231f20", "#0a2a8b", "development", ["ST", "CB", "RB"], "Keep punching above weight from Talcahuano"],
    ["Unión Española", "UES", 51, "#e2001a", "#ffffff", "domestic", ["ST", "CB", "CDM"], "Return to the international places"],
    ["Cobresal", "COB", 50, "#f7761f", "#231f20", "survival", ["ST", "CB", "CM"], "Defy the altitude and stay in the top half"],
    ["O'Higgins", "OHI", 50, "#6cabdd", "#231f20", "midTable", ["ST", "CM", "CB"], "Get Rancagua back into continental football"],
    ["Coquimbo Unido", "COQ", 50, "#f7c600", "#231f20", "midTable", ["ST", "CB", "LB"], "Turn a historic season into a title challenge"],
    ["Audax Italiano", "AUD", 50, "#0a7d3c", "#ffffff", "development", ["ST", "RW", "CB"], "Develop and sell before the window shuts"],
    ["Everton de Viña del Mar", "EVE", 49, "#0a2a8b", "#f7c600", "survival", ["ST", "CB", "GK"], "Stay in the Primera División"],
    ["Ñublense", "NUB", 48, "#e2001a", "#231f20", "survival", ["ST", "CB", "CDM"], "Keep Chillán in the first division"],
  ]),

  /* ---------------- Peru · Liga 1 ---------------- */
  worldLeague("per-l1", "Liga 1", "Peru", 1, 50, [
    ["Universitario de Deportes", "UNI", 56, "#f0e2c4", "#8b1e3f", "domestic", ["ST", "CB", "CM"], "Win a fourth straight national title"],
    ["Alianza Lima", "ALI", 56, "#0a2a8b", "#ffffff", "domestic", ["ST", "CAM", "CB"], "Take the title back to La Victoria"],
    ["Sporting Cristal", "CRI", 55, "#6cabdd", "#ffffff", "development", ["ST", "CB", "CM"], "Win with a squad built in the academy"],
    ["FBC Melgar", "MEL", 51, "#e2001a", "#231f20", "domestic", ["ST", "CB", "CDM"], "Use the Arequipa altitude to reach the Libertadores"],
    ["Cienciano", "CIE", 49, "#e2001a", "#ffffff", "domestic", ["ST", "CM", "CB"], "Bring continental nights back to Cusco"],
    ["Universidad César Vallejo", "UCV", 48, "#0a2a8b", "#ffffff", "midTable", ["ST", "CB", "RB"], "Finish in the Sudamericana places"],
    ["Sport Huancayo", "HUY", 47, "#e2001a", "#ffffff", "midTable", ["ST", "CB", "CM"], "Make the Huancayo altitude count again"],
    ["Cusco FC", "CUS", 47, "#231f20", "#f7c600", "midTable", ["ST", "CAM", "CB"], "Break into the championship play-offs"],
    ["Deportivo Garcilaso", "GAR", 46, "#e2001a", "#f7c600", "survival", ["ST", "CB", "CDM"], "Establish a young club in Liga 1"],
    ["Atlético Grau", "GRA", 46, "#ffffff", "#e2001a", "survival", ["ST", "CB", "GK"], "Keep Piura in the top flight"],
    ["Sport Boys", "BOY", 45, "#f06eaa", "#231f20", "survival", ["ST", "CB", "CM"], "Survive and give Callao something to cheer"],
    ["ADT Tarma", "ADT", 45, "#f7c600", "#231f20", "survival", ["ST", "CB", "CDM"], "Stay in Liga 1 for another season"],
  ]),

  /* ---------------- Ecuador · Serie A ---------------- */
  worldLeague("ecu-sa", "Serie A", "Ecuador", 1, 52, [
    ["Independiente del Valle", "IDV", 60, "#231f20", "#0a2a8b", "development", ["ST", "CB", "CM"], "Produce a world-class teenager and sell him to Europe"],
    ["LDU Quito", "LDU", 58, "#ffffff", "#231f20", "domestic", ["ST", "CAM", "CB"], "Add another continental trophy in Quito"],
    ["Barcelona SC", "BSC", 57, "#f7c600", "#231f20", "domestic", ["ST", "CB", "CM"], "Win the title in front of the biggest crowds in Ecuador"],
    ["CS Emelec", "EME", 54, "#0a2a8b", "#ffffff", "domestic", ["ST", "CB", "CDM"], "Rebuild and win the Guayaquil clásico"],
    ["SD Aucas", "AUC", 49, "#e2001a", "#f7c600", "domestic", ["ST", "CM", "CB"], "Get back into the championship play-offs"],
    ["Delfín SC", "DEL", 48, "#0a2a8b", "#f7c600", "midTable", ["ST", "CB", "RB"], "Qualify for the Copa Sudamericana"],
    ["Universidad Católica del Ecuador", "UCQ", 48, "#0a2a8b", "#ffffff", "development", ["ST", "CB", "CM"], "Trade academy players and stay in the top half"],
    ["Deportivo Cuenca", "CUE", 47, "#e2001a", "#ffffff", "midTable", ["ST", "CB", "CDM"], "Finish in the top six"],
    ["Orense SC", "ORE", 46, "#0a7d3c", "#ffffff", "survival", ["ST", "CB", "GK"], "Keep Machala in the Serie A"],
    ["Macará", "MAC", 46, "#6cabdd", "#ffffff", "survival", ["ST", "CB", "CM"], "Avoid the relegation play-off"],
    ["Mushuc Runa", "MUS", 45, "#0a7d3c", "#f7c600", "survival", ["ST", "CB", "CDM"], "Survive on the smallest budget in the division"],
    ["Técnico Universitario", "TEC", 45, "#e2001a", "#ffffff", "survival", ["ST", "GK", "CB"], "Stay up and keep Ambato in the first division"],
  ]),

  /* ---------------- Paraguay · Primera División ---------------- */
  worldLeague("par-pd", "Primera División", "Paraguay", 1, 52, [
    ["Olimpia", "OLI", 58, "#ffffff", "#231f20", "domestic", ["ST", "CB", "CM"], "Win the league and chase a fourth Libertadores"],
    ["Cerro Porteño", "CER", 58, "#e2001a", "#0a2a8b", "domestic", ["ST", "CAM", "CB"], "Beat Olimpia to the title"],
    ["Club Libertad", "LIB", 56, "#f7c600", "#231f20", "development", ["ST", "CB", "CM"], "Keep winning titles with home-grown players"],
    ["Club Guaraní", "GUA", 53, "#f7c600", "#231f20", "domestic", ["ST", "CB", "CDM"], "Return to the Libertadores group stage"],
    ["Nacional Asunción", "NAS", 50, "#0a2a8b", "#ffffff", "midTable", ["ST", "CB", "CM"], "Reach the international places again"],
    ["Sportivo Luqueño", "LUQ", 47, "#f7c600", "#0a2a8b", "midTable", ["ST", "CB", "RB"], "Finish in the top half"],
    ["Sportivo Trinidense", "TRI", 46, "#e2001a", "#ffffff", "survival", ["ST", "CB", "CDM"], "Consolidate in the Primera División"],
    ["Sportivo Ameliano", "AML", 46, "#0a7d3c", "#ffffff", "development", ["ST", "CB", "CM"], "Sell young players and stay competitive"],
    ["General Caballero JLM", "GCB", 45, "#0a7d3c", "#ffffff", "survival", ["ST", "CB", "GK"], "Avoid relegation on the average table"],
    ["2 de Mayo", "DDM", 45, "#e2001a", "#ffffff", "survival", ["ST", "CB", "CM"], "Keep Pedro Juan Caballero in the top flight"],
    ["Tacuary", "TAC", 45, "#0a7d3c", "#ffffff", "survival", ["ST", "CB", "CDM"], "Survive another campaign"],
    ["Recoleta", "REC", 44, "#e2001a", "#231f20", "survival", ["ST", "GK", "CB"], "Stay up as a newly promoted side"],
  ]),

  /* ---------------- Saudi Arabia · Saudi Pro League ---------------- */
  worldLeague("sau-pl", "Saudi Pro League", "Saudi Arabia", 1, 66, [
    ["Al Hilal", "HIL", 78, "#0a47a9", "#ffffff", "showcase", ["ST", "CB", "CM"], "Win the AFC Champions League with a squad of global names"],
    ["Al Nassr", "NSR", 76, "#f7c600", "#0a2a8b", "showcase", ["CB", "CDM", "RW"], "Deliver the league title the superstars were signed for"],
    ["Al Ittihad", "ITT", 74, "#231f20", "#f7c600", "showcase", ["ST", "CB", "CAM"], "Defend the championship in Jeddah"],
    ["Al Ahli", "AHL", 73, "#0a7d3c", "#ffffff", "showcase", ["ST", "CB", "CM"], "Turn continental success into a domestic title"],
    ["Al Qadsiah", "QAD", 66, "#f7c600", "#0a2a8b", "showcase", ["ST", "CB", "CDM"], "Break into the big four"],
    ["Al Shabab", "SHB", 65, "#ffffff", "#231f20", "showcase", ["ST", "CAM", "CB"], "Qualify for the AFC Champions League Elite"],
    ["Al Ettifaq", "ETT", 63, "#0a7d3c", "#ffffff", "showcase", ["ST", "CM", "CB"], "Finish in the continental places"],
    ["Al Taawoun", "TAW", 61, "#f7761f", "#ffffff", "midTable", ["ST", "CB", "CM"], "Repeat a top-four finish"],
    ["Al Fateh", "FAT", 60, "#0a7d3c", "#ffffff", "midTable", ["ST", "CB", "CDM"], "Comfortable top-half finish"],
    ["Al Fayha", "FAY", 58, "#ffffff", "#0a2a8b", "midTable", ["ST", "CB", "RB"], "Stay clear of the relegation fight"],
    ["Al Khaleej", "KHA", 57, "#0a2a8b", "#ffffff", "midTable", ["ST", "CM", "CB"], "Establish the club in mid-table"],
    ["Al Riyadh", "RIY", 56, "#ffffff", "#0a7d3c", "survival", ["ST", "CB", "GK"], "Stay in the Saudi Pro League"],
    ["Damac", "DAM", 56, "#0a47a9", "#ffffff", "survival", ["ST", "CB", "CDM"], "Beat the drop with an experienced spine"],
    ["Al Wehda", "WEH", 55, "#e2001a", "#ffffff", "survival", ["ST", "CB", "CM"], "Survive the season in Mecca"],
    ["Al Okhdood", "OKH", 54, "#f7c600", "#231f20", "survival", ["ST", "CB", "GK"], "Avoid an immediate return to the first division"],
    ["Al Najma", "NJM", 54, "#0a2a8b", "#ffffff", "survival", ["ST", "CB", "CDM"], "Stay up in the first season back"],
  ]),

  /* ---------------- Japan · J1 League ---------------- */
  worldLeague("jpn-j1", "J1 League", "Japan", 1, 62, [
    ["Kawasaki Frontale", "KAW", 66, "#0a5ba8", "#231f20", "development", ["ST", "CB", "CM"], "Win the J1 League back and go deep in Asia"],
    ["Vissel Kobe", "KOB", 66, "#8b1a2b", "#231f20", "showcase", ["ST", "CB", "CAM"], "Retain the title with a marquee forward"],
    ["Yokohama F. Marinos", "YOK", 65, "#0a2a8b", "#e2001a", "development", ["ST", "CB", "CDM"], "Get back to the top of the J1 League"],
    ["Urawa Red Diamonds", "URA", 65, "#e2001a", "#231f20", "showcase", ["ST", "CAM", "CB"], "Give the biggest support in Japan a league title"],
    ["Kashima Antlers", "KAS", 64, "#8b1a2b", "#0a2a8b", "development", ["ST", "CB", "CM"], "End the trophy drought at Japan's most decorated club"],
    ["Sanfrecce Hiroshima", "HIR", 63, "#6a2c8e", "#ffffff", "development", ["ST", "RW", "CB"], "Convert cup form into a league title"],
    ["FC Tokyo", "TOK", 62, "#0a2a8b", "#e2001a", "midTable", ["ST", "CB", "CM"], "Get back into the AFC places"],
    ["Gamba Osaka", "GAM", 62, "#0a2a8b", "#231f20", "development", ["ST", "CB", "CDM"], "Bring the academy generation back to the top four"],
    ["Cerezo Osaka", "CEZ", 61, "#f06eaa", "#231f20", "development", ["ST", "CM", "CB"], "Produce another Japan international"],
    ["Nagoya Grampus", "NAG", 61, "#e2001a", "#f7c600", "midTable", ["ST", "CAM", "CB"], "Finish in the top six"],
    ["Kashiwa Reysol", "KSW", 60, "#f7c600", "#231f20", "development", ["ST", "CB", "CM"], "Turn a strong season into a title challenge"],
    ["Machida Zelvia", "MCH", 59, "#0a2a8b", "#6cabdd", "midTable", ["ST", "CB", "CDM"], "Prove the rise up the J.League is permanent"],
    ["Kyoto Sanga", "KYO", 59, "#6a2c8e", "#ffffff", "midTable", ["ST", "CB", "CM"], "Establish the club in the top half"],
    ["Avispa Fukuoka", "FUK", 58, "#0a2a8b", "#f7c600", "midTable", ["ST", "CB", "RB"], "Stay comfortably clear of relegation"],
    ["Shimizu S-Pulse", "SHI", 58, "#f7a600", "#231f20", "midTable", ["ST", "CB", "CM"], "Consolidate after promotion"],
    ["Albirex Niigata", "NII", 57, "#f7c600", "#0a2a8b", "survival", ["ST", "CB", "CDM"], "Stay in J1"],
    ["Hokkaido Consadole Sapporo", "SAP", 56, "#e2001a", "#231f20", "survival", ["ST", "CB", "GK"], "Bring top-flight football back to Sapporo"],
    ["Shonan Bellmare", "SHO", 55, "#0a7d3c", "#6cabdd", "survival", ["ST", "CB", "CM"], "Beat the drop again"],
  ]),

  /* ---------------- South Korea · K League 1 ---------------- */
  worldLeague("kor-k1", "K League 1", "South Korea", 1, 58, [
    ["Ulsan HD", "ULS", 64, "#0a2a8b", "#f7c600", "midTable", ["ST", "CB", "CM"], "Win a fourth straight K League title"],
    ["Jeonbuk Hyundai Motors", "JEO", 64, "#0a7d3c", "#ffffff", "showcase", ["ST", "CAM", "CB"], "Reclaim the title and win the AFC Champions League"],
    ["Pohang Steelers", "POH", 61, "#e2001a", "#231f20", "development", ["ST", "CB", "CM"], "Get back to an Asian final"],
    ["FC Seoul", "SEO", 61, "#e2001a", "#231f20", "showcase", ["ST", "CB", "CDM"], "Fill the World Cup Stadium with a title race"],
    ["Gangwon FC", "GAN", 58, "#f7761f", "#231f20", "development", ["ST", "CB", "CM"], "Repeat the run to the top of the table"],
    ["Gwangju FC", "GWA", 57, "#f7c600", "#231f20", "development", ["ST", "CB", "RB"], "Stay in Asia on the smallest budget in the league"],
    ["Daejeon Hana Citizen", "DAE", 57, "#6a2c8e", "#ffffff", "midTable", ["ST", "CB", "CM"], "Finish in the championship round"],
    ["Gimcheon Sangmu", "GIM", 57, "#e2001a", "#ffffff", "midTable", ["ST", "CB", "CDM"], "Keep the army side in the top six"],
    ["Suwon FC", "SUW", 56, "#0a2a8b", "#e2001a", "midTable", ["ST", "CB", "CM"], "Stay in the top half"],
    ["Jeju SK", "JEJ", 56, "#f7761f", "#ffffff", "midTable", ["ST", "CB", "GK"], "Get back into the championship round"],
    ["Daegu FC", "DAG", 55, "#6cabdd", "#231f20", "survival", ["ST", "CB", "CDM"], "Avoid the relegation play-off"],
    ["FC Anyang", "ANY", 53, "#6a2c8e", "#ffffff", "survival", ["ST", "CB", "GK"], "Survive the first seasons in K League 1"],
  ]),

  /* ---------------- China · Chinese Super League ---------------- */
  worldLeague("chn-sl", "Chinese Super League", "China", 1, 54, [
    ["Shanghai Port", "SHP", 60, "#e2001a", "#231f20", "showcase", ["ST", "CB", "CM"], "Retain the title and go deep in Asia"],
    ["Shanghai Shenhua", "SHS", 59, "#0a2a8b", "#ffffff", "showcase", ["ST", "CAM", "CB"], "Win the Shanghai derby and the championship"],
    ["Beijing Guoan", "BJG", 58, "#0a7d3c", "#ffffff", "showcase", ["ST", "CB", "CDM"], "Return the capital club to the title race"],
    ["Shandong Taishan", "SDT", 58, "#f7761f", "#231f20", "showcase", ["ST", "CB", "CM"], "Win the league and the FA Cup double"],
    ["Chengdu Rongcheng", "CDR", 57, "#e2001a", "#f7c600", "midTable", ["ST", "CB", "RW"], "Turn the loudest crowd in China into a title"],
    ["Zhejiang FC", "ZHE", 55, "#0a7d3c", "#ffffff", "development", ["ST", "CB", "CM"], "Keep promoting from the best academy in the country"],
    ["Wuhan Three Towns", "WUH", 55, "#e2001a", "#231f20", "midTable", ["ST", "CB", "CDM"], "Get back among the challengers"],
    ["Tianjin Jinmen Tiger", "TJT", 53, "#e2001a", "#f7c600", "midTable", ["ST", "CB", "CM"], "Finish in the top half"],
    ["Henan FC", "HEN", 52, "#e2001a", "#ffffff", "survival", ["ST", "CB", "GK"], "Stay in the Chinese Super League"],
    ["Changchun Yatai", "CCY", 51, "#e2001a", "#0a2a8b", "survival", ["ST", "CB", "CDM"], "Beat the drop in the north-east"],
    ["Qingdao Hainiu", "QHN", 51, "#f7c600", "#0a2a8b", "survival", ["ST", "CB", "CM"], "Survive another top-flight season"],
    ["Meizhou Hakka", "MZH", 50, "#e2001a", "#f7c600", "survival", ["ST", "CB", "GK"], "Keep a small club in the CSL"],
    ["Dalian Yingbo", "DAL", 50, "#0a2a8b", "#ffffff", "survival", ["ST", "CB", "CDM"], "Re-establish Dalian in the top flight"],
    ["Qingdao West Coast", "QWC", 49, "#0a2a8b", "#f7761f", "survival", ["ST", "CB", "CM"], "Avoid an immediate relegation"],
  ]),

  /* ---------------- Australia · A-League Men ---------------- */
  worldLeague("aus-al", "A-League Men", "Australia", 1, 52, [
    ["Melbourne City", "MCY", 58, "#6cabdd", "#ffffff", "development", ["ST", "CB", "CM"], "Feed the global network and win the Premiership"],
    ["Melbourne Victory", "MVC", 57, "#0a2a8b", "#f7c600", "showcase", ["ST", "CAM", "CB"], "Win the Grand Final in front of a record crowd"],
    ["Sydney FC", "SYD", 57, "#6cabdd", "#0a2a8b", "showcase", ["ST", "CB", "CM"], "Get the Sky Blues back to the top"],
    ["Central Coast Mariners", "CCM", 56, "#f7c600", "#0a2a8b", "development", ["ST", "CB", "RB"], "Keep producing champions on the smallest budget"],
    ["Western Sydney Wanderers", "WSW", 55, "#e2001a", "#231f20", "midTable", ["ST", "CB", "CDM"], "Win a first Grand Final for the RBB"],
    ["Adelaide United", "ADL", 54, "#e2001a", "#231f20", "development", ["ST", "CB", "CM"], "Blood the academy and reach the finals series"],
    ["Brisbane Roar", "BRI", 53, "#f7761f", "#231f20", "midTable", ["ST", "CB", "CM"], "Return to the finals series"],
    ["Perth Glory", "PER", 52, "#6a2c8e", "#ffffff", "survival", ["ST", "CB", "GK"], "Climb off the bottom of the ladder"],
    ["Auckland FC", "AUC", 52, "#0a2a8b", "#6cabdd", "showcase", ["ST", "CB", "CM"], "Make the expansion club a Premiership winner"],
    ["Wellington Phoenix", "WEL", 52, "#f7c600", "#231f20", "midTable", ["ST", "CB", "CDM"], "Make the finals from across the Tasman"],
    ["Macarthur FC", "MCR", 51, "#0a2a8b", "#f7c600", "midTable", ["ST", "CB", "CM"], "Turn cup success into league consistency"],
    ["Newcastle Jets", "NEW", 51, "#e2001a", "#0a2a8b", "survival", ["ST", "CB", "GK"], "Rebuild and get out of the bottom two"],
    ["Western United", "WES", 50, "#0a7d3c", "#231f20", "survival", ["ST", "CB", "CDM"], "Stabilise the club and stay in the finals race"],
  ]),

  /* ---------------- Morocco · Botola Pro ---------------- */
  worldLeague("mar-bo", "Botola Pro", "Morocco", 1, 54, [
    ["Raja Club Athletic", "RAJ", 60, "#0a7d3c", "#ffffff", "domestic", ["ST", "CB", "CM"], "Win the Botola and the CAF Champions League"],
    ["Wydad AC", "WAC", 60, "#e2001a", "#ffffff", "domestic", ["ST", "CAM", "CB"], "Take the Casablanca derby and a third continental crown"],
    ["RS Berkane", "RSB", 58, "#f7761f", "#231f20", "domestic", ["ST", "CB", "CM"], "Retain the CAF Confederation Cup"],
    ["AS FAR", "FAR", 57, "#0a2a8b", "#ffffff", "domestic", ["ST", "CB", "CDM"], "Bring the title back to Rabat"],
    ["Maghreb de Fès", "MAS", 52, "#0a7d3c", "#ffffff", "development", ["ST", "CB", "CM"], "Bring academy players through to the first team"],
    ["FUS Rabat", "FUS", 52, "#0a2a8b", "#ffffff", "development", ["ST", "CB", "RB"], "Sell young talent to Europe and finish in the top five"],
    ["Olympique Safi", "OCS", 50, "#0a2a8b", "#ffffff", "midTable", ["ST", "CB", "CM"], "Qualify for the CAF competitions"],
    ["Hassania Agadir", "HUS", 50, "#e2001a", "#ffffff", "midTable", ["ST", "CB", "CDM"], "Finish in the top half"],
    ["Moghreb Tétouan", "MAT", 49, "#e2001a", "#ffffff", "survival", ["ST", "CB", "GK"], "Stay in the Botola Pro"],
    ["Ittihad Tanger", "IRT", 49, "#e2001a", "#ffffff", "survival", ["ST", "CB", "CM"], "Beat the drop in Tangier"],
    ["Chabab Mohammédia", "SCC", 48, "#0a7d3c", "#e2001a", "survival", ["ST", "CB", "CDM"], "Consolidate in the top flight"],
    ["Union Touarga", "UTS", 47, "#f7c600", "#231f20", "survival", ["ST", "CB", "GK"], "Survive another Botola season"],
    ["Renaissance Zemamra", "RCZ", 47, "#0a7d3c", "#ffffff", "survival", ["ST", "CB", "CM"], "Keep a small-town club in the Botola"],
    ["Olympique Dcheira", "ODC", 46, "#0a2a8b", "#ffffff", "survival", ["ST", "GK", "CB"], "Avoid an immediate relegation"],
  ]),

  /* ---------------- Egypt · Premier League ---------------- */
  worldLeague("egy-pl", "Egyptian Premier League", "Egypt", 1, 56, [
    ["Al Ahly", "AHY", 68, "#e2001a", "#ffffff", "domestic", ["ST", "CB", "CM"], "Win the CAF Champions League for a twelfth time"],
    ["Zamalek", "ZAM", 65, "#ffffff", "#e2001a", "domestic", ["ST", "CAM", "CB"], "Beat Al Ahly to the league title"],
    ["Pyramids FC", "PYR", 63, "#0a2a8b", "#ffffff", "showcase", ["ST", "CB", "CM"], "Turn continental glory into a first league title"],
    ["Ismaily", "ISM", 55, "#f7761f", "#ffffff", "domestic", ["ST", "CB", "CDM"], "Bring the Dervishes back to the top four"],
    ["Al Masry", "MSR", 55, "#0a7d3c", "#ffffff", "domestic", ["ST", "CB", "CM"], "Qualify for the CAF competitions from Port Said"],
    ["Ceramica Cleopatra", "CCL", 53, "#0a2a8b", "#f7c600", "midTable", ["ST", "CB", "RB"], "Finish in the top six"],
    ["ZED FC", "ZED", 51, "#0a7d3c", "#ffffff", "development", ["ST", "CB", "CM"], "Build a young side that sells abroad"],
    ["National Bank of Egypt", "NBE", 51, "#0a7d3c", "#f7c600", "midTable", ["ST", "CB", "CDM"], "Stay comfortably in mid-table"],
    ["Modern Future", "MOD", 50, "#0a2a8b", "#ffffff", "midTable", ["ST", "CB", "CM"], "Push into the European-style top half"],
    ["Smouha", "SMO", 50, "#0a2a8b", "#ffffff", "survival", ["ST", "CB", "GK"], "Keep Alexandria in the Premier League"],
    ["ENPPI", "ENP", 50, "#e2001a", "#ffffff", "survival", ["ST", "CB", "CDM"], "Stay clear of the relegation zone"],
    ["Pharco FC", "PHA", 49, "#6a2c8e", "#ffffff", "survival", ["ST", "CB", "CM"], "Establish the club in the top flight"],
    ["El Gouna", "GOU", 48, "#f7c600", "#0a2a8b", "survival", ["ST", "CB", "GK"], "Survive on the Red Sea"],
    ["Baladiyat El Mahalla", "MAH", 47, "#0a7d3c", "#ffffff", "survival", ["ST", "GK", "CB"], "Beat the drop after promotion"],
  ]),

  /* ---------------- Tunisia · Ligue 1 ---------------- */
  worldLeague("tun-l1", "Ligue Professionnelle 1", "Tunisia", 1, 50, [
    ["Espérance de Tunis", "EST", 62, "#f7c600", "#e2001a", "domestic", ["ST", "CB", "CM"], "Win the league again and reach a CAF final"],
    ["Club Africain", "CAF", 57, "#e2001a", "#ffffff", "domestic", ["ST", "CAM", "CB"], "Take the Tunis derby and the championship"],
    ["Étoile du Sahel", "ESS", 56, "#e2001a", "#f7c600", "development", ["ST", "CB", "CM"], "Sell to Europe and challenge for the title"],
    ["CS Sfaxien", "CSS", 55, "#231f20", "#ffffff", "domestic", ["ST", "CB", "CDM"], "Bring continental football back to Sfax"],
    ["US Monastir", "USM", 51, "#0a2a8b", "#ffffff", "midTable", ["ST", "CB", "CM"], "Qualify for the CAF Confederation Cup"],
    ["Stade Tunisien", "STU", 50, "#e2001a", "#ffffff", "midTable", ["ST", "CB", "RB"], "Finish in the play-off group"],
    ["CA Bizertin", "CAB", 48, "#f7c600", "#231f20", "survival", ["ST", "CB", "CDM"], "Stay in Ligue 1"],
    ["US Ben Guerdane", "UBG", 47, "#0a7d3c", "#ffffff", "survival", ["ST", "CB", "GK"], "Keep a southern club in the top flight"],
    ["Olympique Béja", "OBE", 47, "#e2001a", "#ffffff", "survival", ["ST", "CB", "CM"], "Avoid the relegation group"],
    ["ES Métlaoui", "ESM", 46, "#0a7d3c", "#ffffff", "survival", ["ST", "CB", "CDM"], "Survive another season"],
    ["AS Gabès", "ASG", 46, "#0a2a8b", "#ffffff", "survival", ["ST", "GK", "CB"], "Consolidate after promotion"],
    ["JS Omrane", "JSO", 45, "#f7c600", "#0a2a8b", "survival", ["ST", "CB", "CM"], "Beat the drop in the capital"],
  ]),

  /* ---------------- Nigeria · NPFL ---------------- */
  worldLeague("nga-npfl", "Nigeria Premier Football League", "Nigeria", 1, 46, [
    ["Enyimba", "ENY", 52, "#0a7d3c", "#ffffff", "domestic", ["ST", "CB", "CM"], "Win the league and get back to the CAF group stage"],
    ["Remo Stars", "REM", 51, "#f7c600", "#231f20", "development", ["ST", "CB", "CDM"], "Defend the title and sell a player to Europe"],
    ["Rivers United", "RVU", 50, "#0a7d3c", "#ffffff", "domestic", ["ST", "CB", "CM"], "Bring the trophy back to Port Harcourt"],
    ["Rangers International", "RAN", 49, "#0a7d3c", "#ffffff", "domestic", ["ST", "CB", "CDM"], "Restore the Flying Antelopes to the top"],
    ["Kano Pillars", "KAN", 48, "#e2001a", "#0a2a8b", "domestic", ["ST", "CB", "CM"], "Make Sani Abacha Stadium unbeatable again"],
    ["Plateau United", "PLU", 48, "#e2001a", "#ffffff", "midTable", ["ST", "CB", "RB"], "Finish in the continental places"],
    ["Shooting Stars", "SSC", 48, "#e2001a", "#ffffff", "domestic", ["ST", "CB", "CM"], "Return the oldest club in Nigeria to the title race"],
    ["Bendel Insurance", "BEN", 47, "#0a2a8b", "#ffffff", "midTable", ["ST", "CB", "CDM"], "Stay in the top six"],
    ["Lobi Stars", "LOB", 47, "#f7761f", "#231f20", "survival", ["ST", "CB", "GK"], "Stay in the NPFL"],
    ["Akwa United", "AKW", 46, "#f7c600", "#231f20", "survival", ["ST", "CB", "CM"], "Climb out of the bottom four"],
    ["Nasarawa United", "NSU", 46, "#f7c600", "#0a7d3c", "survival", ["ST", "CB", "CDM"], "Beat the drop in Lafia"],
    ["Sunshine Stars", "SUS", 45, "#f7c600", "#0a7d3c", "survival", ["ST", "CB", "GK"], "Survive another NPFL campaign"],
    ["Katsina United", "KAT", 45, "#0a2a8b", "#ffffff", "survival", ["ST", "CB", "CM"], "Keep top-flight football in Katsina"],
    ["Abia Warriors", "ABI", 45, "#0a7d3c", "#f7c600", "survival", ["ST", "GK", "CB"], "Avoid relegation"],
  ]),

  /* ---------------- Ghana · Premier League ---------------- */
  worldLeague("gha-pl", "Ghana Premier League", "Ghana", 1, 44, [
    ["Asante Kotoko", "KOT", 50, "#e2001a", "#ffffff", "domestic", ["ST", "CB", "CM"], "Win the league and return to the CAF Champions League"],
    ["Hearts of Oak", "HRT", 49, "#e2001a", "#f7c600", "domestic", ["ST", "CAM", "CB"], "Take the Super Clash and the title"],
    ["Medeama SC", "MED", 47, "#f7c600", "#0a2a8b", "development", ["ST", "CB", "CM"], "Sell to Europe and stay a title contender"],
    ["Aduana Stars", "ADU", 46, "#f7c600", "#231f20", "domestic", ["ST", "CB", "CDM"], "Make Dormaa a fortress again"],
    ["Bechem United", "BEC", 45, "#0a2a8b", "#f7c600", "midTable", ["ST", "CB", "RB"], "Finish in the continental places"],
    ["Samartex", "SAM", 45, "#0a7d3c", "#f7c600", "development", ["ST", "CB", "CM"], "Turn a young side into champions"],
    ["Dreams FC", "DRE", 45, "#f7c600", "#0a2a8b", "development", ["ST", "CB", "CDM"], "Repeat the run to a CAF semi-final"],
    ["Great Olympics", "OLY", 44, "#0a2a8b", "#ffffff", "midTable", ["ST", "CB", "CM"], "Stay in the top half in Accra"],
    ["Nations FC", "NAT", 44, "#0a7d3c", "#ffffff", "development", ["ST", "CB", "CM"], "Build an academy side that wins the league"],
    ["Berekum Chelsea", "BER", 44, "#0a2a8b", "#ffffff", "survival", ["ST", "CB", "GK"], "Stay in the Premier League"],
    ["Karela United", "KAR", 43, "#f7761f", "#231f20", "survival", ["ST", "CB", "CDM"], "Beat the drop in the Western Region"],
    ["Legon Cities", "LEG", 43, "#6cabdd", "#ffffff", "survival", ["ST", "GK", "CB"], "Survive another season in Accra"],
  ]),

  /* ---------------- Cameroon · Elite One ---------------- */
  worldLeague("cmr-e1", "Elite One", "Cameroon", 1, 44, [
    ["Coton Sport Garoua", "COT", 50, "#0a7d3c", "#ffffff", "domestic", ["ST", "CB", "CM"], "Win the league and represent Cameroon in Africa"],
    ["Union Douala", "UND", 46, "#e2001a", "#ffffff", "domestic", ["ST", "CB", "CDM"], "Bring the title back to Douala"],
    ["Canon Yaoundé", "CAN", 46, "#e2001a", "#f7c600", "domestic", ["ST", "CB", "CM"], "Restore the biggest name in Cameroonian football"],
    ["Victoria United", "VIC", 45, "#0a2a8b", "#f7c600", "domestic", ["ST", "CB", "RB"], "Defend the championship in Limbe"],
    ["PWD Bamenda", "PWD", 44, "#0a2a8b", "#ffffff", "midTable", ["ST", "CB", "CM"], "Finish in the top five"],
    ["Fauve Azur Elite", "FAE", 43, "#0a2a8b", "#ffffff", "development", ["ST", "CB", "CDM"], "Develop players the national team can pick"],
    ["Colombe Sportive", "COS", 43, "#6cabdd", "#ffffff", "midTable", ["ST", "CB", "CM"], "Stay in the top half"],
    ["Dynamo Douala", "DYN", 43, "#0a2a8b", "#ffffff", "survival", ["ST", "CB", "GK"], "Stay in Elite One"],
    ["APEJES Academy", "APE", 42, "#f7c600", "#0a7d3c", "development", ["ST", "CB", "CM"], "Sell an academy graduate abroad"],
    ["Stade Renard", "STR", 42, "#e2001a", "#ffffff", "survival", ["ST", "CB", "CDM"], "Beat the drop in Melong"],
    ["Aigle Royal", "AIG", 42, "#f7c600", "#231f20", "survival", ["ST", "CB", "GK"], "Survive another Elite One season"],
    ["Bamboutos", "BAM", 42, "#0a7d3c", "#ffffff", "survival", ["ST", "GK", "CB"], "Keep Mbouda in the first division"],
  ]),

  /* ---------------- Senegal · Ligue 1 ---------------- */
  worldLeague("sen-l1", "Ligue 1", "Senegal", 1, 44, [
    ["Génération Foot", "GEN", 46, "#0a7d3c", "#f7c600", "development", ["ST", "CB", "CM"], "Send the next Sadio Mané to Europe"],
    ["ASC Jaraaf", "JAR", 46, "#0a7d3c", "#ffffff", "domestic", ["ST", "CB", "CDM"], "Win the league and reach the CAF group stage"],
    ["Diambars FC", "DIA", 45, "#0a2a8b", "#ffffff", "development", ["ST", "CB", "CM"], "Build the whole XI from the academy"],
    ["Casa Sports", "CAS", 45, "#0a7d3c", "#ffffff", "domestic", ["ST", "CB", "CM"], "Bring the title back to Ziguinchor"],
    ["Teungueth FC", "TEU", 45, "#0a2a8b", "#f7c600", "domestic", ["ST", "CB", "CDM"], "Qualify for the CAF Champions League"],
    ["Dakar Sacré-Cœur", "DSC", 44, "#e2001a", "#ffffff", "development", ["ST", "CB", "CM"], "Develop and sell another Europe-bound teenager"],
    ["AS Pikine", "PIK", 43, "#0a2a8b", "#ffffff", "midTable", ["ST", "CB", "RB"], "Finish in the top five"],
    ["Guédiawaye FC", "GUE", 43, "#e2001a", "#ffffff", "midTable", ["ST", "CB", "CM"], "Stay in the top half"],
    ["US Gorée", "GOR", 43, "#0a2a8b", "#f7c600", "survival", ["ST", "CB", "GK"], "Stay in Ligue 1"],
    ["Linguère", "LIN", 42, "#f7c600", "#0a7d3c", "survival", ["ST", "CB", "CDM"], "Beat the drop in Saint-Louis"],
    ["Wally Daan", "WAL", 42, "#0a7d3c", "#f7c600", "survival", ["ST", "CB", "CM"], "Survive another season"],
    ["HLM Dakar", "HLM", 42, "#0a2a8b", "#ffffff", "survival", ["ST", "GK", "CB"], "Keep the club in the first division"],
  ]),

  /* ---------------- South Africa · Premier Soccer League ---------------- */
  worldLeague("rsa-psl", "Premier Soccer League", "South Africa", 1, 52, [
    ["Mamelodi Sundowns", "SUN", 62, "#f7c600", "#0a7d3c", "elite", ["ST", "CB", "CM"], "Win the CAF Champions League and an eighth straight league title"],
    ["Orlando Pirates", "PIR", 58, "#231f20", "#ffffff", "domestic", ["ST", "CAM", "CB"], "End the wait for a league title"],
    ["Kaizer Chiefs", "CHF", 56, "#f7c600", "#231f20", "domestic", ["ST", "CB", "CDM"], "Get Amakhosi back into the title race"],
    ["SuperSport United", "SSU", 53, "#0a2a8b", "#ffffff", "development", ["ST", "CB", "CM"], "Develop internationals and finish in the top eight"],
    ["Stellenbosch FC", "STE", 53, "#e2001a", "#231f20", "development", ["ST", "CB", "RB"], "Sell to Europe and stay in continental football"],
    ["Sekhukhune United", "SEK", 51, "#0a7d3c", "#f7c600", "midTable", ["ST", "CB", "CM"], "Break into the top four"],
    ["AmaZulu", "AMZ", 51, "#0a7d3c", "#ffffff", "midTable", ["ST", "CB", "CDM"], "Bring Durban back into the top eight"],
    ["Golden Arrows", "ARR", 50, "#f7c600", "#231f20", "midTable", ["ST", "CB", "CM"], "Finish in the top half"],
    ["TS Galaxy", "TSG", 49, "#e2001a", "#231f20", "midTable", ["ST", "CB", "CDM"], "Turn cup-winning history into league consistency"],
    ["Polokwane City", "POL", 49, "#e2001a", "#231f20", "survival", ["ST", "CB", "GK"], "Stay in the PSL"],
    ["Chippa United", "CHP", 48, "#0a2a8b", "#e2001a", "survival", ["ST", "CB", "CM"], "Beat the drop in Gqeberha"],
    ["Richards Bay", "RIC", 48, "#0a7d3c", "#ffffff", "survival", ["ST", "CB", "CDM"], "Survive another top-flight season"],
    ["Marumo Gallants", "MAR", 47, "#f7c600", "#0a7d3c", "survival", ["ST", "CB", "GK"], "Avoid the promotion play-offs"],
    ["Magesi FC", "MAG", 47, "#0a2a8b", "#f7c600", "survival", ["ST", "GK", "CB"], "Keep a newly promoted side in the PSL"],
  ]),
];
